# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmCli < Formula
  desc "A unified CLI for Claude and Gemini LLMs"
  homepage "https://github.com/fabriqaai/llm-cli"
  version "0.2.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fabriqaai/llm-cli/releases/download/v0.2.7/llm-cli_0.2.7_darwin_amd64.tar.gz"
      sha256 "9090ef34cc8e72484f626a15b4cd50979a44314a6d3f732176c590013fa13371"

      def install
        bin.install "llm-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fabriqaai/llm-cli/releases/download/v0.2.7/llm-cli_0.2.7_darwin_arm64.tar.gz"
      sha256 "aa6663237a498ad3f248043efe868c5860c28df94e88d579196b168a859321cf"

      def install
        bin.install "llm-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fabriqaai/llm-cli/releases/download/v0.2.7/llm-cli_0.2.7_linux_amd64.tar.gz"
      sha256 "99d0ff9b7818cdb30e3c19b8701eef195d0236e0083a10235a79654cbe915936"
      def install
        bin.install "llm-cli"
      end
    end
  end

  test do
    system "#{bin}/llm-cli", "version"
  end
end
