# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmCli < Formula
  desc "A unified CLI for Claude and Gemini LLMs"
  homepage "https://github.com/fabriqaai/llm-cli"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fabriqaai/llm-cli/releases/download/v0.2.5/llm-cli_0.2.5_darwin_amd64.tar.gz"
      sha256 "b2d52e689044e8252044887f7cdf8847fd98088d9c8ef32d08206f496d7aa68b"

      def install
        bin.install "llm-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fabriqaai/llm-cli/releases/download/v0.2.5/llm-cli_0.2.5_darwin_arm64.tar.gz"
      sha256 "9b63397abb72c2d02ef0ac3d73f70ecf17c16046d06ebb2d4d25d69ca9b2bdb0"

      def install
        bin.install "llm-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fabriqaai/llm-cli/releases/download/v0.2.5/llm-cli_0.2.5_linux_amd64.tar.gz"
      sha256 "2580a7aad3e7316f55a1f370977b5a901f8967ada96cad84dcf83fe01a162c81"
      def install
        bin.install "llm-cli"
      end
    end
  end

  test do
    system "#{bin}/llm-cli", "version"
  end
end
