# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LlmCli < Formula
  desc "A unified CLI for Claude and Gemini LLMs"
  homepage "https://github.com/fabriqaai/llm-cli"
  version "0.2.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/fabriqaai/llm-cli/releases/download/v0.2.4/llm-cli_0.2.4_darwin_amd64.tar.gz"
      sha256 "726e8b1eb33ea5467ce7da4223ee1de95ceb8cfedc1b24a79b38c72cbc8150e0"

      def install
        bin.install "llm-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/fabriqaai/llm-cli/releases/download/v0.2.4/llm-cli_0.2.4_darwin_arm64.tar.gz"
      sha256 "2719ede82f5c0282456997561a05b3809ccabcfac3175f1312032e0e5f4c8387"

      def install
        bin.install "llm-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/fabriqaai/llm-cli/releases/download/v0.2.4/llm-cli_0.2.4_linux_amd64.tar.gz"
      sha256 "59a189a65d3a1f1df8951c37924fbd9a5fb36d043f9d4e3ade0e450cd226eb8d"
      def install
        bin.install "llm-cli"
      end
    end
  end

  test do
    system "#{bin}/llm-cli", "version"
  end
end
